# Generated by Django 4.1.4 on 2022-12-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='prescription_doctor',
            new_name='Doctor Name',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='prescription_patient',
            new_name='Patient Name',
        ),
    ]
